version: '3.9'
services:
  yorum-analiz:
    build: ./otel_yorum_analiz
    container_name: yorum_analiz_api
    ports:
      - "5000:5000"
    volumes:
      - ./otel_yorum_analiz:/app
    restart: always

  backend:
    build: ./travel-backend
    container_name: travel_backend
    ports:
      - "8080:8080"
    restart: always
