# Base image
FROM python:3.10-slim

# Çalışma dizini
WORKDIR /app

# Gereksinimleri kopyala ve yükle
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Uygulama dosyalarını kopyala
COPY . .

# Flask uygulamasını başlat
CMD ["python", "app/api.py"]
